import type { Metadata } from "next";
import Header  from '../components/Header';
import { Poppins } from 'next/font/google';
import "./globals.css";

const poppins = Poppins({
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'], 
  subsets: ['latin'],
  variable: '--font-poppins',
});

export const metadata: Metadata = {
  title: "Round Up Reviews",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`bg-[#F5F5F5] ${poppins.variable}  antialiased`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
